name: Auto Request Review

on:
  pull_request_target:
    types: [opened, synchronized, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps: []
